### ISSUE TITLE
User Provided Services

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#1010]
Going thru the walkthru and playing with @simonleung8's plugin stuff I think we may need to consider some changes to user provided services.  A couple of things jump out at me:

- the yaml for creating a UPS Instance is this:
```
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: ups-instance
  namespace: test-ns
spec:
  serviceClassName: user-provided-service
  planName: default
```
- The `planName` being in there feels odd since UPS shouldn't really have plans at all. 
- There are no creds in there. I'm assuming this is an oversight. While the code will populate things with some interesting default values, we shouldn't really do that - we should just let the creds be empty if that's what they want.

I'm not convinced that deploying a ups-broker is the right approach.  Requiring a "plan" when its not needed gives a bad UX. Requiring people to deploy an entire service just to get UPSs (which is just an echo service) feels like overkill to me.

I'm wondering if we should treat UPS as a special kind of resource so that we expose them to the user in a more natural way w/o forcing them to do things like pass-in dummy data.

CF does this today too.
