### ISSUE TITLE
Service plan updates in broker not propagating to clusterserviceplan objects

### ISSUE THREAD

**Issue by dymurray** [kubernetes-incubator/service-catalog#1388]
When a service plan is updated from the Broker the service catalog fails to reconcile the new clusterserviceplan object which causes that object to never receive the updated service plan. 

When a service plan changes I would expect the service catalog to recognize the change, and reconcile the object changes.

**Comment by dymurray** [comment]
FYI to workaround this we can delete and recreate the broker but that should not be the standard practice of reconciling service plan changes.

**Comment by pmorie** [comment]
@dymurray Can you supply some supporting information to help diagnose this?  YAML dumps, controller logs, etc.

**Comment by dymurray** [comment]
@pmorie Here is the relevant log from the controller manager pod:
```
I1013 17:34:59.486881       1 controller_broker.go:410] ClusterServiceBroker "aws-service-broker": Reconciling ClusterServiceClass (K8S: "b2d15f47ece73514892b87d150008a97" ExternalName: "dh-sqs-apb")
I1013 17:34:59.486887       1 controller_broker.go:592] ClusterServiceBroker "aws-service-broker": Found existing ClusterServiceClass (K8S: "b2d15f47ece73514892b87d150008a97" ExternalName: "dh-sqs-apb"); updating
I1013 17:34:59.682722       1 request.go:462] Throttling request took 195.76584ms, request: PUT:https://172.30.0.1:443/apis/servicecatalog.k8s.io/v1beta1/clusterserviceclasses/b2d15f47ece73514892b87d150008a97 
I1013 17:34:59.686050       1 controller_broker.go:427] ClusterServiceBroker "aws-service-broker": Reconciled ClusterServiceClass (K8S: "b2d15f47ece73514892b87d150008a97" ExternalName: "dh-sqs-apb")
```

It says that it successfully reconciles the serviceclass dh-sqs-apb but that clusterserviceclass' associated clusterserviceplan does NOT get updated appropiately and displays the old plan information in the UI. What is strange is that this doesn't happen for every updated clusterserviceinstance, just randomly on some. Like I said deleting the broker and recreating the broker fixes the issue as it gets the Plan information from scratch.

**Comment by pmorie** [comment]
@dymurray Can you provide some information about which fields you expected to change?

**Comment by dymurray** [comment]
@pmorie Yes the new Service Plan had an entirely different set of parameters listed which failed to show up.

**Comment by pmorie** [comment]
@dymurray I think we need more information from the logs - for example, I don't see any messages about reconciling plans, only classes.  Can you update with more of the log context?

**Comment by dymurray** [comment]
@pmorie 

No errors are displayed in the controller manager:
```
I1013 18:32:15.522308       1 controller_broker.go:360] ClusterServiceBroker "aws-service-broker": reconciling ClusterServicePlan (K8S: "b4007074bc8c8628e4514d0d4fc3252e" ExternalName: "standard")
I1013 18:32:15.522314 1 controller_broker.go:656] ClusterServiceBroker "aws-service-broker": Found existing ClusterServicePlan "b4007074bc8c8628e4514d0d4fc3252e"; updating
I1013 18:32:15.715582 1 request.go:462] Throttling request took 193.141305ms, request: PUT:https://172.30.0.1:443/apis/servicecatalog.k8s.io/v1beta1/clusterserviceplans/b4007074bc8c8628e4514d0d4fc3252e 
I1013 18:32:15.722036 1 controller_broker.go:375] ClusterServiceBroker "aws-service-broker": Reconciled ClusterServicePlan (K8S: "b4007074bc8c8628e4514d0d4fc3252e" ExternalName: "standard")
```

Output from hitting the catalog endpoint on the broker:
```
      "plans": [
        {
          "id": "b4007074bc8c8628e4514d0d4fc3252e",
          "name": "standard",
          "description": "Managed SQS Queue (Standard)",
          "metadata": {
            "cost": "$0.00",
            "displayName": "Standard",
            "longDescription": "Standard SQS APB",
            "schemas": {
              "service_binding": {
                "create": {
                  "openshift_form_definition": []
                }
              },
              "service_instance": {
                "create": {
                  "openshift_form_definition": [
                    {
                      "title": "Standard Queue Parameters",
                      "type": "fieldset",
                      "items": [
                        "stack_identifier",
                        "region",
                        "DelaySeconds",
                        "MaximumMessageSize",
                        "MessageRetentionPeriod",
                        "ReceiveMessageWaitTimeSeconds",
                        "UsedeadletterQueue",
                        "VisibilityTimeout"
                      ]
                    }
                  ]
                },
                "update": {}
```
Output from `oc get clusterserviceplans` for the associated service plan:
```
  description: Managed SQS Queue (Standard)
  externalID: b4007074bc8c8628e4514d0d4fc3252e
  externalMetadata:
    cost: $0.00
    displayName: Standard
    longDescription: Standard SQS APB
    schemas:
      service_binding:
        create:
          openshift_form_definition: []
      service_instance:
        create:
          openshift_form_definition:
          - items:
            - key: aws_access_key
              type: password
            - key: aws_secret_key
              type: password
            title: AWS Account Information
            type: fieldset
          - items:
            - stack_identifier
            - region
            - DelaySeconds
            - MaximumMessageSize
            - MessageRetentionPeriod
            - ReceiveMessageWaitTimeSeconds
            - UsedeadletterQueue
            - VisibilityTimeout
            title: Standard Queue Parameters
            type: fieldset
        update: {}
  externalName: standard
  free: false
  instanceCreateParameterSchema:
    $schema: http://json-schema.org/draft-04/schema
```

The `aws_access_key` and `aws_secret_key` are from a secret that gets created after the broker has reported the initial serviceplan to the service catalog. Once the secret gets created and the service plan updates is when we don't see the updated `clusterserviceplan`.

**Comment by pmorie** [comment]
@dymurray I'm not sure what kind of update you expected to see here - can you elaborate?

**Comment by dymurray** [comment]
@pmorie as you can see the output from the catalog endpoint on the broker shows that 
 `openshift_form_definition` associated with the APBs serviceInstace should only have:
```
          - items:
            - stack_identifier
            - region
            - DelaySeconds
            - MaximumMessageSize
            - MessageRetentionPeriod
            - ReceiveMessageWaitTimeSeconds
            - UsedeadletterQueue
            - VisibilityTimeout
            title: Standard Queue Parameters
            type: fieldset
```

Instead it has:
```
          - items:
            - key: aws_access_key
              type: password
            - key: aws_secret_key
              type: password
            title: AWS Account Information
            type: fieldset
          - items:
            - stack_identifier
            - region
            - DelaySeconds
            - MaximumMessageSize
            - MessageRetentionPeriod
            - ReceiveMessageWaitTimeSeconds
            - UsedeadletterQueue
            - VisibilityTimeout
            title: Standard Queue Parameters
            type: fieldset
```

The service plan's data in the broker has a different parameter list than the service catalog. The Service catalog is displaying the old data and never updating the clusterServicePlan to remove the two parameters which are stale (`aws_access_key` and `aws_secret_key`).

To be clear, this is happening because when the broker bootstraps it reports the APB's service plan to the service catalog. This list *includes* the two `aws_***_key` params. A secret is then created which removes these two parameters from the broker's service plan. This change is never reconciled and updated in the service catalog's `clusterServicePlan`.

Please let me know if there is any information I can help clear up.
