### ISSUE TITLE
updateStrategy of apiserver and controller-manager are not consistent

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes-incubator/service-catalog#1491]
I noticed the updateStrategy of apiserver is RollingUpdate, but controller-manager is OnDelete, I think they should be consistent.

In daemonset yaml files:
controller-manager:

```
  updateStrategy:
    type: OnDelete
```

apiserver:

```
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
