### ISSUE TITLE
ServiceBinding parametersFrom attribute is not validated for having no keys

### ISSUE THREAD

**Issue by mijajasinski** [kubernetes-incubator/service-catalog#1691]
Service Catalog version used: 1.3

If you try to create a ServiceInstance with parametersFrom having empty key:

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-instance
  namespace: my-namespace
spec:
  externalClusterServiceClassName: my-class
  externalClusterServicePlanName: my-plan
  parametersFrom:
    - secretKeyRef:
        name: my-secret
```
You get an error:

> The ServiceInstance "my-instance" is invalid: spec.parametersFrom.secretKeyRef.key: Required value: key is required

On the other hand, if you attempt to create a ServiceBinding with empty key:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: my-binding
  namespace: default
spec:
  instanceRef:
    name: my-instance
  parametersFrom:
  - secretKeyRef:
      name: my-secret
  secretName: binding-secret
```
Even though, this is incomplete information, binding gets created and the "parametersFrom" looks like that:
```
  parametersFrom:
  - secretKeyRef:
      key: ""
      name: my-secret
```

I believe the second scenario should return an error, akin to what happens in case of ServiceInstance.
