### ISSUE TITLE
svcat chokes on azure auth provider

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#1818]
I'm going to assume it chokes on all non-default auth providers:

```
$ svcat get classes
Error: No Auth Provider found for name "azure"
```

Relevant section from my kubeconfig:

```
users:
- name: my-cluster-admin
  user:
    auth-provider:
      config:
        access-token: <redacted>
        apiserver-id: <redacted>
        client-id: <redacted>
        expires-in: "3599"
        expires-on: "1520461261"
        refresh-token: <redacted>
        tenant-id: <redacted>
      name: azure
```
