### ISSUE TITLE
Empty ServiceBinding conditions when ServiceInstance points to non-existent plan

### ISSUE THREAD

**Issue by luksa** [kubernetes-incubator/service-catalog#1908]
If I create a `ServiceInstance` that points to a non-existent plan, and then create a `ServiceBinding`, the controller simply logs an error and doesn't update the status of the `ServiceBinding`:
```
  status:
    asyncOpInProgress: false
    conditions: []
    orphanMitigationInProgress: false
    reconciledGeneration: 0
    unbindStatus: NotRequired
``` 

Relevant lines in the controller: https://github.com/kubernetes-incubator/service-catalog/blob/dfec6deb28e04ba1b0ec7dadc614f1a6844a4105/pkg/controller/controller_binding.go#L198-L201
