### ISSUE TITLE
[question][help wanted] How to block ServiceBinding deletion

### ISSUE THREAD

**Issue by mszostok** [kubernetes-incubator/service-catalog#1954]
Hi

*This is a nutshell of our issue:*

In our K8s platform we added a new custom resource (CR) which depends on the ServiceBinding. When such CR is created we want to block the deletion of the ServiceBinding connected with it. 

*Details* 

Scenario  - **creation**
1. Create a ServiceInstance
2. Create a ServiceBinding
3. Create a ServiceBindingUsage (our CR)

Scenario – **deletions, current state**
1. Delete a ServiceInstance (will be block if the correlated ServiceBinding exists)
2. Delete a ServiceBinding – deleted without any checks
3. Delete a ServiceBindingUsage – deleted without any checks

Scenario - **deletions, desired state**
1. Delete a ServiceInstance (will be block if the correlated ServiceBinding exists)
2. Delete a ServiceBinding – (will be block if the correlated ServiceBindingUsages exists)
3. Delete a ServiceBindingUsage – deleted without any checks (in the future graceful deletion will also be handled by us)

We thought that we can achieve the flow of the last scenario by adding our new finalizer to the ServiceBinding finalizer list, so we did that. Thanks to that the ServiceBinding still exists in etcd but... unfortunately the Service Catalog deletes the Secret and the ServiceBinding has the following status:
```yaml
Status:
  Async Op In Progress:  false
  Conditions:
    Last Transition Time:         2018-04-18T10:14:59Z
    Message:                      The binding was deleted successfully
    Reason:                       UnboundSuccessfully
    Status:                       False
    Type:                         Ready
  Orphan Mitigation In Progress:  false
  Reconciled Generation:          2
  Unbind Status:                  Succeeded
```

And that breaks our flow because the Service Catalog always executes the finalizer logic for the ServiceBinding, and we do not know how to block it without using "hacks".

Additionally, we found such comment in the source code for version 0.0.11
https://github.com/kubernetes-incubator/service-catalog/blob/v0.0.13/pkg/controller/controller_binding.go#L286-L292

and the best part of this comment is the following lines:
> // (..) we proceed with the soft delete
> // only if it's "our turn--" i.e. only if the finalizer we care about is at
> // the head of the finalizers list.

In the newest versions this idea was dropped and not implemented.

Could you elaborate on how we can handle the last-described scenario?

Maybe we can extend the Service Catalog with a feature which checks if the list of finalizers equals 1 and that this finalizer is the `FinalizerServiceCatalog`. Only then the Service Catalog should execute the finalizer logic for the ServiceBinding.

Thank you in advance
