### ISSUE TITLE
extension-apiserver-authentication not found

### ISSUE THREAD

**Issue by jicowan** [kubernetes-incubator/service-catalog#2120]
I tried installing service catalog onto a k8s v1.10 cluster from the helm chart svc-cat/catalog.  The API server fails to start with the following error: 
```
01:31:44.138448       1 authentication.go:232] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
Error: configmaps "extension-apiserver-authentication" not found
```
There is a configmap in the kube-system namespace called catalog.v1 but so far as I can tell the chart didn't create a configmap called extension-apiserver-authentication.

**Comment by jboyd01** [comment]
Helm should be creating the rbac to allow Catalog API server to read this.  Within charts/catalog/templates/rbac.yaml:
```yaml
- apiVersion: {{template "rbacApiVersion" . }}
  kind: RoleBinding
  metadata:
    name: "servicecatalog.k8s.io:apiserver-authentication-reader"
    namespace: kube-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: "{{ .Values.apiserver.serviceAccount }}"
    namespace: "{{ .Release.Namespace }}"
```
Can you see if this was created?

`kubectl get roles  -n kube-system extension-apiserver-authentication-reader -o yaml`

`kubectl get rolebinding servicecatalog.k8s.io:apiserver-authentication-reader -n kube-system -o yaml`

If you remove catalog (`helm delete --purge catalog`) and redeploy adding --debug to the helm install command, you'll get more verbose output that might help narrow in on the issue
