### ISSUE TITLE
Memory leak in Controller Manager when registered malfunctioning broker

### ISSUE THREAD

**Issue by aszecowka** [kubernetes-incubator/service-catalog#2276]
# Bug Report 

**What happened**:
Controller Manager pod is constantly restarting when I registered a malfunctioning broker (broker responds with status code HTTP 500 on "/v2/catalog" endpoint). Memory usage for ControllerManager goes up to 30MB and then it is restarted - probably because of defined memory limit. 
To magnify this problem, I created ~80 malfunctioning brokers, and in 35 minutes ControllerManager was restared 8 times.

**What you expected to happen**:
Controller Manager does not restart

**How to reproduce it (as minimally and precisely as possible)**:
Install Service Catalog on minikube:
`minikube start --extra-config=apiserver.authorization-mode=RBAC`
`helm init`
`helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm install svc-cat/catalog \
    --name catalog --namespace catalog`

Write a malfunctioning broker:
```main.go
package main

import (
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/v2/catalog", getCatalog)
	log.Fatal(http.ListenAndServe(":8080", nil))
}

func getCatalog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusInternalServerError)
}

```
Create Dockerfile
```
FROM alpine:3.7
COPY ./servicebroker-linux /root/broker

ENTRYPOINT ["/root/broker"]
```

Build broker image:
`eval (minikube docker-env)`
`GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o servicebroker-linux --ldflags="-s" . `
`docker build -t "nasty-app:1.0.0" .`

Create deployment:
`kubectl create -f deploy.yaml`
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nasty-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasty-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nasty-app
    spec:
      containers:
      - name: broker
        image: "nasty-app:1.0.0"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
```
Create service:
`kubectl create -f service.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: nasty-service
spec:
  type: NodePort
  selector:
    app: nasty-app
  ports:
    - name: broker
      port: 80
      targetPort: 8080
      protocol: TCP

```

Create ClusterServiceBroker:
`kubectl create -f charts/broker.yaml`
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: nasty-broker
spec:
  url: http://nasty-service.default.svc.cluster.local
```
Broker status:
`kubectl describe clusterservicebroker nasty-broker`
```
...
Status:
  Conditions:
    Last Transition Time:  2018-08-14T11:55:11Z
    Message:               Error fetching catalog.Error getting broker catalog: Status: 500; ErrorMessage: <nil>; Description: <nil>; ResponseError: unexpected end of JSON input
    Reason:                ErrorFetchingCatalog
    Status:                False
    Type:                  Ready
```
Here you can see that pod is restarting:
`kubectl get pods -n catalog`
```
NAME                                                  READY     STATUS             RESTARTS   AGE
catalog-catalog-apiserver-6bccbd5786-4grsg            2/2       Running            0          35m
catalog-catalog-controller-manager-794cc648b9-9wlrl   0/1       CrashLoopBackOff   8          35m
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- service-catalog version: 0.1.29
- Cloud provider or hardware configuration: minikube v0.28.2
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? yes
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
looks fine
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values? 
see above
- Are you trying to use ALPHA features? Did you enable them?
no
