### ISSUE TITLE
Mismatch between v1beta1/CatalogRestrictions and internal/CatalogRestrictions

### ISSUE THREAD

**Issue by luksa** [kubernetes-incubator/service-catalog#2299]
The order of the properties is reversed. In `v1beta1/types.go`:
```go
type CatalogRestrictions struct {
	// ServiceClass represents a selector for plans, used to filter catalog re-lists.
	ServiceClass []string `json:"serviceClass,omitempty"`    <-----
	// ServicePlan represents a selector for classes, used to filter catalog re-lists.
	ServicePlan []string `json:"servicePlan,omitempty"`      <-----
}
```
vs. `servicecatalog/types.go`:
```go
type CatalogRestrictions struct {
	// ServiceClass represents a selector for plans, used to filter catalog re-lists.
	ServicePlan []string    <-----
	// ServicePlan represents a selector for classes, used to filter catalog re-lists.
	ServiceClass []string   <-----
}
```

Because of this, the conversion between the two types isn't correct. But luckily, this doesn't seem to have any ill effects, since we're performing the wrong conversion two times. 

But, the error does become apparent when you try to create a broker with an invalid restriction:

For example, applying the following ClusterServiceBroker spec:
```
spec:
  url: http://ups-broker-ups-broker.ups-broker.svc.cluster.local
  catalogRestrictions:
    serviceClass:
    - "invalid class restriction"
```
throws the following error:
```
The ClusterServiceBroker "ups-broker-invalid" is invalid: spec.catalogRestrictions.servicePlan: Invalid value: []string(nil): unable to parse requirement: found 'class', expected: '=', '!=', '==', 'in', notin'
```
Note that the error shows `servicePlan` instead of `serviceClass` and that the invalid value is `[]string(nil)` instead of `[]string{"invalid class restriction"}`.

Similarly, if the spec contains `catalogRestrictions.servicePlan`:
```
spec:
  url: http://ups-broker-ups-broker.ups-broker.svc.cluster.local
  catalogRestrictions:
    servicePlan:
    - "invalid plan restriction"
```
this is the error:
```
The ClusterServiceBroker "ups-broker-invalid" is invalid: spec.catalogRestrictions.serviceClass: Invalid value: []string{"invalid plan restriction"}: unable to parse requirement: found 'plan', expected: '=', '!=', '==', 'in', notin'
```

This time, the error mentions `catalogRestrictions.serviceClass` instead of `servicePlan`. But at least here, the correct invalid value is printed.

I'll send a PR shortly. We can discuss the fix there (my hunch is that we may run into a few problems).
