### ISSUE TITLE
Add support for Pod-Preset - aka Pod Injection Policy

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#266]
Just a spot for pointers to the real work so its easy for people to find the other issues, PRs and design docs.

k8s/features issue:  https://github.com/kubernetes/features/issues/162
k8s/community PR: https://github.com/kubernetes/community/pull/254
k8s/kubernetes PR: https://github.com/kubernetes/kubernetes/pull/41931

**Comment by pmorie** [comment]
I think we should move this to the MVP 2 milestone.  The resource will be in Kubernetes 1.6, so we should be able to implement this once we do #413.  Thoughts?

**Comment by duglin** [comment]
the title of the milestone doesn't matter as much to me - I'm more interested in us hooking it up as soon as we rebase on kube 1.6 - and I'd like that sooner rather than later.

**Comment by pmorie** [comment]
@duglin 

> I'm more interested in us hooking it up as soon as we rebase on kube 1.6 - and I'd like that sooner rather than later.

Yep, we're in 100% agreement about that.  That will be in mvp-2.

**Comment by arschles** [comment]
We have all talked about this before, so I'll repeat here - I'd like support for pod-presets to be built completely behind a feature flag.

**Comment by arschles** [comment]
This will be done with #413

**Comment by arschles** [comment]
Assigned to you @pmorie since you'll complete this with #413

**Comment by arschles** [comment]
This is a duplicate of #637. Closing

**Comment by pmorie** [comment]
Re-opened because this is the original issue.

**Comment by pmorie** [comment]
After doing some exploration in #670, I have found an issue that means we will have to rethink the first version of this integration (ie, the first alpha integration that we do at this moment) because of a snag that I hit once I begin plumbing through the `PodPresetSpec` field in the API.

The fundamental issue is that there is no good way to validate an API type from a core API group (except for the metav1 group, which exports validations) outside the core API server.  No versioned validations are exported.  You cannot even do something like vendoring the kube code and converting to the internal format, because the package that we consume the API types from is transformed when `client-go` is exported from the main kubernetes repo.  I opened https://github.com/kubernetes/kubernetes/issues/44995 to try to solve this problem, but after some thought, I do not think exporting code for validations is the right thing.  I have some ideas about the right solution, but I will keep the discussion of those on the linked issue.

Long-term, we need to be able to validate API types like this outside the core API server.  Once we can do that, we can easily just embed a `PodPresetTemplateSpec` in our API surface and validate it all over town.

However, for now, there is not a good way to integrate the `PodPresetSpec` type itself into our API surface.  I have a strong desire and business need to be able to leverage pod preset ASAP in our API, so I have been thinking about stopgap measures.  One fairly easy stop gap is to add support only for the new `envFrom` feature that is present in kubernetes 1.6.  Given a name for a pod preset and a label selector for that pod preset in our API, we could generate a pod preset that would add a new `envFrom` for the secret referenced in the binding.  

Here's a sketch of what that would look like in our API:

```go
type BindingSpec struct {
	// other fields omitted

	AlphaPodPresetName *string
	AlphaPodPresetLabelSelector *metav1.LabelSelector
}
```

We can validate `LabelSelector` type with an exported validation from the `metav1` group, and of course, the name is easy to validate with a ton of leakage of information into our validation code (it's the same as the validation for secret name, which we already do).

So, for an example, given the following binding:

```yaml
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: test-binding
  namespace: test-ns
spec:
  instanceRef:
    name: test-instance
  secretName: my-secret
  alphaPodPresetName: my-pod-preset
  alphaPodPresetLabelSelector: 
    matchLabels:
      app: frontend
```

We would produce a `PodPreset` like so:

```yaml
kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: my-pod-preset
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: frontend
  envFrom:
    - secretRef:
        name: my-secret
```

This would at least be usable to give us coverage of an 80% (or 80% of 80%) use-case, and I think would be very usable to people.  I would also be fine with plumbing through a prefix field for the `EnvFrom` if people need that.
