### ISSUE TITLE
How do people update PodPreSet labelSelectors?

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#797]
Let's say I have a Deployment that looks like this:
```
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        ...
```
I then want to bind this to my service instance so I create a binding with a PodPresetSpec that looks like this:
```
spec:
  selector:
    matchLabels:
      app: myapp
  env:
    ...
```
The key point being that the label selector needs to be the same for both the Deployment and the PodPreset in the Binding.

Now let's say the user wants to modify the LabelSelectors of the Deployment, what's the best way to do this?  I suspect the answer is that they first should update the PodPreset spec in the Binding with the new labelSelector and then do the same for the Deployment. Doing it the other way around might miss some pods that are created during this time. Of course, if the new value for the labelSelector isn't additive then we may miss some pods this way too.

I'm wondering if there are cases like this in other parts of Kube where the same bit of info is duplicated and how they deal with it? 

This solution, while do-able, feels less than optimal since it require some level of sync'ing updates between two resources ; requires the user to remember to do the binding first ; and is error prone because asking people to keep two bits of data in-sync is always error prone.

I don't think we can get rid of the freedom the express things in this way - there may be reasons why the person doesn't want the two resources to be in-sync, but I do think those are the less common cases.

I think we should optimize for the more common case and help the user. I'm wondering if instead of having the PodPreset have a copy of the labelSelector, I wonder if we could have the PodPreset point to the resource that has the labelSelector we want to match. For example:
```
spec:
  selectorFrom: deployment/myApp
  env:
    ...
```
or something like that.  Then the user just needs to update one piece of data and not two. To be clear, I'm not suggesting we get rid of the labelSelector in PodPreset, rather make "selectorFrom" be an alternative to it - but only one of the two can be specified at a time.

Thoughts?
