### ISSUE TITLE
Unable to register service broker on kub1.6 

### ISSUE THREAD

**Issue by ajayapte** [kubernetes-incubator/service-catalog#900]
I'm running kub 1.6.  I installed helm charts for service catalog and then for ups-broker from github.  When I try to register service broker I get an error stating the service is not yet ready to accept requests.  My broker registration yaml 
```
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: ups-broker
spec:
  url: http://ups-broker-ups-broker.catalog.svc.cluster.local
```
I guess this is kub 1.6 RBAC issue. 
When I look at controller logs I see this repeatedly - 
```
E0525 22:32:22.859707       1 leaderelection.go:229] error retrieving resource lock kube-system/service-catalog-controller-manager: User "system:serviceaccount:catalog:default" cannot get endpoints in the namespace "kube-system". (get endpoints service-catalog-controller-manager)
I0525 22:32:22.859720       1 leaderelection.go:185] failed to acquire lease kube-system/s
```
And in API server logs I see this repeatedly - 
```
E0525 22:32:28.358034       1 reflector.go:201] github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/informers/factory.go:70: Failed to list *v1.Namespace: User "system:serviceaccount:catalog:default" cannot list namespaces at the cluster scope. (get namespaces)
```

I will try creating a service account with appropriate permissions and have deployments/services use it.  Has anyone seen this on 1.6?
