### ISSUE TITLE
Service-Catalog appears to not be passing valid broker auth credentials

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#948]
The meta azure service broker's catalog endpoint returns with the following JSON (abridged):

```json
{
	"services": [{
		"id": "3befc561-4f0c-4df3-ab26-48ac4e366b1c",
		"name": "azure-documentdb",
		"description": "Azure DocumentDb Service",
		"bindable": true,
		"plans": [{...}]
        }]
}
```

This appears to be a valid catalog response body, but when the (v0.0.10) controller hits it, the `Broker` gets the following condition set on it:

```yaml
    message: Error syncing catalog from Broker. Error getting catalog payload for
      broker "masb"; received zero services; at least one service is required
    reason: ErrorSyncingCatalog
```

More debugging details to come here. I have reproduced this issue with the steps outlined at https://github.com/arschles/meta-azure-service-broker-helm, using the `v0.0.10` version of the controller.
