### ISSUE TITLE
Problem with env vars for creds

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#969]
Been pondering https://github.com/kubernetes-incubator/service-catalog/issues/881 and I think there might be other issues we need to deal with.  Looking at a typical credentials from the spec:
```
{
  "credentials": {
    "uri": "mysql://mysqluser:pass@mysqlhost:3306/dbname",
    "username": "mysqluser",
    "password": "pass",
    "host": "mysqlhost",
    "port": 3306,
    "database": "dbname"
  }
}
```
Right now with our current podpreset stuff each one of those properties will be an environment variable. If we have more than one binding there's a good change that there will be a conflict for common names like "username" and "password". This is a big problem.

CF doesn't have this issue because they wrapper each binding before they stick it in VCAP_SERVICES. See https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES  - in particular the example at the bottom. So, there's a clear separation between each binding and each is clearly identifiable.

This would seem to indicate that our current approach is broken when there is more than one binding - and since I don't think we should have a different cred-look-up-mechanism based on how many bindings there are - I think this might cause our current entire env var approach to be broken.  

Having the secrets mounted as volumes should avoid this problem as long as the user specifies exactly where each binding is mounted.  Then they can know exactly where to look for each binding.

Just brainstorming/rambling a bit.... 
- the most obvious solution would be to prefix each env var with something to ensure each is unique, perhaps with the binding name
- we could create one env var per binding - a VCAP_SERVICES-like thing but one per binding. This avoids needing to solve #881 
- we could ban the use of env vars  :-)
- we could solve #881 and just copy what CF does for env vars

More thinking is needed, but I think this might raise the important of getting Volume support for our PodPreset stuff in if we can't find a good solution for this.

**Comment by nilebox** [comment]
@duglin that's the limitation only if you embed the PodPreset template into Binding.
Before this feature was introduced such problem was easy-peasy to tackle with when you declared a PodPreset manually:
```yaml
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
name: podpreset1
spec:
selector:
    matchLabels:
    role: app
envFrom:
- prefix: BINDING1_
    secretRef:
    name: binding1-secret
- prefix: BINDING2_
    secretRef:
    name: binding2-secret
```
